name: d5e6u7ya8
favicon: null
layout_spectrum: 0.602396433474496
typography_spectrum: 0.9494150665123016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8381170586217195
  lightness: 0.2178103942424059
  saturation: 0.11976840603165329
  rhythmicContrast: 0.2703607575967908
purpose: []
